name: Bug report
description: Report a reproducible problem
title: "[Bug] "
labels: ["bug"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What happened?
      placeholder: A clear and concise bug description
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Provide exact steps
      placeholder: |
        1. Open app
        2. Click ...
        3. See error
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: App version
      placeholder: e.g. v0.1.0
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Windows version
      placeholder: e.g. Windows 11 23H2
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant logs/screenshots
      description: Attach logs or screenshots if possible

